name: Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - id: cache-id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ steps.cache-id.outputs.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc git cmake make libtool g++ perl coreutils \
            libcurl4-openssl-dev libbz2-dev liblzma-dev zlib1g-dev

      - name: Install package with docs dependencies
        run: |
          SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0 uv pip install -e ".[dev]"

      - name: Build and deploy
        run: |
          uv run mkdocs build
          uv run mkdocs gh-deploy --force
