name: Run Python Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/milne-group/quantnado-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install package
        run: pip install --no-cache-dir -e ".[dev]" --no-deps

      - name: Run tests
        run: pytest tests
